#!/bin/sh
# design-sync's cssEntry/tokensGlob are read from inside PKG_DIR only — a
# hard, intentional security bound (package-build.mjs: "a path anywhere
# under workspaceRoot would let a malicious dep's config exfiltrate
# project-root files"). @lew-ds/lds-react (this sync's pkg, now that
# @lew-ds/lds itself is framework-free — see NOTES.md) ships no CSS of its
# own by design; it depends on @lew-ds/lds's. So a REAL copy has to live
# inside packages/lds-react for cssEntry/tokensGlob to resolve at all.
#
# This is design-sync-only plumbing, not a product decision: it does NOT
# touch packages/lds-react's committed package.json, exports map, or
# public API — packages/lds-react/css/ is gitignored and regenerated by
# this script, never committed. Re-run before every build/resync (a fresh
# clone or an upstream @lew-ds/lds CSS change won't have it otherwise).
set -e
cd "$(dirname "$0")/.."

rm -rf packages/lds-react/css
cp -r packages/lds/css packages/lds-react/css

echo "prepare-css: copied packages/lds/css -> packages/lds-react/css (gitignored, design-sync only)"
